### ISSUE TITLE
Pip Install on windows broken

### ISSUE THREAD

**Issue by peterdku** [t4ngo/dragonfly#44]
When i try to install dragonfly on windows via PIP i get the following error:
```
DEPRECATION: --no-install, --no-download, --build, and --no-clean are deprecated.  See https://github.com/pypa/pip/issues/906.
Downloading/unpacking dragonfly
  Running setup.py (path:E:\Userfiles\Username\Appdata\pycharm-packaging0.tmp\dragonfly\setup.py) egg_info for package dragonfly
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "E:\Userfiles\Username\Appdata\pycharm-packaging0.tmp\dragonfly\setup.py", line 63, in <module>
        from ez_setup import use_setuptools
      File ".\ez_setup.py", line 98
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "E:\Userfiles\Username\Appdata\pycharm-packaging0.tmp\dragonfly\setup.py", line 63, in <module>

    from ez_setup import use_setuptools

  File ".\ez_setup.py", line 98

    except pkg_resources.VersionConflict, e:

                                        ^

SyntaxError: invalid syntax
```

**Comment by evfredericksen** [comment]
I'm assuming you're trying to install on Python 3? Dragonfly only works for Python 2.
